// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'cancelButton': string;
  'checkboxLabel': string;
  'checkboxRow': string;
  'dataLoadState': string;
  'field': string;
  'fieldMoreSpaceBefore': string;
  'form': string;
  'heading': string;
  'input': string;
  'requiredMark': string;
  'section': string;
  'sectionDivider': string;
  'sectionDividerMoreSpaceBefore': string;
  'submissionError': string;
  'submitButton': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
