// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'countriesCompound': string;
  'detailField': string;
  'detailLabel': string;
  'jsonPre': string;
  'nestedCountriesBasic': string;
}
export const cssExports: CssExports;
export default cssExports;
