// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dbSourceField': string;
  'dbSourceLabel': string;
  'dbSourceSelect': string;
  'header': string;
  'tab': string;
  'tabActive': string;
  'tabList': string;
  'tabPanel': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
