import type { AppWindowName } from "@/appConstants/appWindows";

// The magic constants auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

// the rule those are generated by is simple - "name" of window is capitalized and then appended with either _WEBPACK_ENTRY (for html file) or with _PRELOAD_WEBPACK_ENTRY (for preload file)
// name of window is same as its key in "appWindows" map

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const ARTIST_WINDOW_WEBPACK_ENTRY: string;
declare const ARTIST_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const ENTRY_WINDOW_WEBPACK_ENTRY: string;
declare const ENTRY_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const TAGS_WINDOW_WEBPACK_ENTRY: string;
declare const TAGS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const LABELS_WINDOW_WEBPACK_ENTRY: string;
declare const LABELS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const appWindows = {
  main_window: {
    preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: MAIN_WINDOW_WEBPACK_ENTRY,
  },
  artist_window: {
    preload: ARTIST_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: ARTIST_WINDOW_WEBPACK_ENTRY,
  },
  entry_window: {
    preload: ENTRY_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: ENTRY_WINDOW_WEBPACK_ENTRY,
  },
  tags_window: {
    preload: TAGS_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: TAGS_WINDOW_WEBPACK_ENTRY,
  },
  labels_window: {
    preload: LABELS_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: LABELS_WINDOW_WEBPACK_ENTRY,
  },
} as const satisfies Record<
  AppWindowName,
  {
    preload: string;
    html: string;
  }
>;

export default appWindows;
