// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailField': string;
  'jsonPre': string;
}
export const cssExports: CssExports;
export default cssExports;
