// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artistsList': string;
  'comment': string;
  'entryPanel': string;
  'field': string;
  'fieldLabel': string;
  'italicNote': string;
  'typesList': string;
  'typesListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
