// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  codeBlock: string;
  codeString: string;
  detailBlock: string;
  detailLabel: string;
  kvKey: string;
  kvRow: string;
  kvValue: string;
  list: string;
  nestedBlock: string;
  nullValue: string;
  objectPanel: string;
  objectRoot: string;
  parseErrorShell: string;
  scalar: string;
  stringShell: string;
}
export const cssExports: CssExports;
export default cssExports;
