// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'codeString': string;
  'detailBlock': string;
  'detailLabel': string;
  'kvKey': string;
  'kvRow': string;
  'kvValue': string;
  'nestedBlock': string;
  'nullValue': string;
  'objectPanel': string;
  'objectRoot': string;
  'parseErrorShell': string;
}
export const cssExports: CssExports;
export default cssExports;
