// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAnotherSlot': string;
  'column': string;
  'controlWithRemove': string;
  'divider': string;
  'input': string;
  'label': string;
  'removeCross': string;
  'removeCrossSlot': string;
  'removeRow': string;
  'removeRowButton': string;
  'rowActions': string;
  'rowBlock': string;
  'rowBlockFirst': string;
  'rowColumns': string;
  'segment': string;
  'slotBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
