CREATE DOMAIN NON_EMPTY_TEXT AS TEXT
CHECK (TRIM(VALUE) <> '');

ALTER TABLE artists
ALTER COLUMN name SET DATA TYPE NON_EMPTY_TEXT;

ALTER TABLE artists
ALTER COLUMN name_for_sorting SET DATA TYPE NON_EMPTY_TEXT;

ALTER TABLE alternative_artist_names
ALTER COLUMN name SET DATA TYPE NON_EMPTY_TEXT;
