// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artistDetails': string;
  'artistInfoBox': string;
  'artistName': string;
}
export const cssExports: CssExports;
export default cssExports;
