import createWindow from "./createWindow";

// The magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const ARTISTS_LIST_WINDOW_WEBPACK_ENTRY: string;
declare const ARTISTS_LIST_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const createArtistsListWindow = () =>
  createWindow({
    preload: ARTISTS_LIST_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: ARTISTS_LIST_WINDOW_WEBPACK_ENTRY,
  });
