import createWindow from "./createWindow";

// The magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const ARTIST_QUERY_WINDOW_WEBPACK_ENTRY: string;
declare const ARTIST_QUERY_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const createArtistQueryWindow = () =>
  createWindow({
    preload: ARTIST_QUERY_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: ARTIST_QUERY_WINDOW_WEBPACK_ENTRY,
  });
