import createWindow from "./createWindow";

// The magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const createMainWindow = () =>
  createWindow({
    preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: MAIN_WINDOW_WEBPACK_ENTRY,
  });
