// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAnotherRow': string;
  'heading': string;
  'jsonField': string;
  'jsonLabel': string;
  'jsonTextarea': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
