// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailBlock': string;
  'detailLabel': string;
  'entriesList': string;
  'entryItem': string;
  'kvKey': string;
  'kvRow': string;
  'kvValue': string;
  'leafValue': string;
  'nestedBlock': string;
  'objectPanel': string;
  'objectRoot': string;
  'parseErrorShell': string;
}
export const cssExports: CssExports;
export default cssExports;
