// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'catNumbersCompound': string;
  'detailBlock': string;
  'detailLabel': string;
  'entriesList': string;
  'entryItem': string;
  'nestedRegions': string;
}
export const cssExports: CssExports;
export default cssExports;
