// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'label': string;
  'root': string;
  'speedPre': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
