// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron': string;
  'chevronExpanded': string;
  'detailsActionButton': string;
  'detailsActionButtonSecondary': string;
  'detailsActions': string;
  'detailsLoading': string;
  'detailsMissing': string;
  'detailsSlide': string;
  'detailsSlideInner': string;
  'detailsSlideOpen': string;
  'entryRelease': string;
  'recentlyAddedBadge': string;
  'recentlyEditedBadge': string;
  'releaseDetailsPanel': string;
  'releaseRemove': string;
  'releaseRow': string;
  'releaseRowMain': string;
  'releaseToggle': string;
  'releaseVersion': string;
}
export const cssExports: CssExports;
export default cssExports;
