// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'label': string;
  'row': string;
  'segment': string;
}
export const cssExports: CssExports;
export default cssExports;
