// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'backdrop': string;
  'button': string;
  'cancel': string;
  'card': string;
  'cardWide': string;
  'confirmDanger': string;
  'confirmDefault': string;
  'description': string;
  'descriptionScrollable': string;
  'error': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
