// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyHint': string;
  'field': string;
  'heading': string;
  'label': string;
  'removeTag': string;
  'section': string;
  'select': string;
  'selectedItem': string;
  'selectedList': string;
}
export const cssExports: CssExports;
export default cssExports;
