// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addRow': string;
  'heading': string;
  'input': string;
  'label': string;
  'removeRow': string;
  'row': string;
  'rows': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
