// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkboxLabel': string;
  'checkboxRow': string;
  'checkboxesRow': string;
  'inlineRow': string;
  'input': string;
  'label': string;
  'segment': string;
  'segmentAmount': string;
}
export const cssExports: CssExports;
export default cssExports;
