// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'checkboxLabel': string;
  'checkboxRow': string;
  'field': string;
  'form': string;
  'formatsLoadState': string;
  'heading': string;
  'input': string;
  'requiredMark': string;
  'section': string;
  'sectionDivider': string;
  'sectionDividerMoreSpaceBefore': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
