// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'field': string;
  'fieldError': string;
  'form': string;
  'input': string;
  'label': string;
  'requiredMark': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
