// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createError': string;
  'createErrorDismiss': string;
  'createNotification': string;
  'createNotificationDismiss': string;
  'deletedNotification': string;
  'deletedNotificationDismiss': string;
  'deletedNotificationText': string;
  'emptyState': string;
  'field': string;
  'panel': string;
  'sectionTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
