// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyState': string;
  'field': string;
  'panel': string;
  'releaseVersion': string;
  'releasesList': string;
  'releasesListItem': string;
  'sectionTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
