// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAnotherFormat': string;
  'divider': string;
  'fieldError': string;
  'formatBlock': string;
  'formatBlockFirst': string;
  'heading': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
