// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailBlock': string;
  'detailField': string;
  'detailLabel': string;
  'detailLabelItalic': string;
  'detailsActionButton': string;
  'detailsActionButtonSecondary': string;
  'detailsActions': string;
  'formatsList': string;
  'relatedReleaseLink': string;
  'relatedReleases': string;
  'relatedReleasesLabel': string;
  'relatedReleasesList': string;
  'relatedReleasesSection': string;
  'releaseDetails': string;
  'tagsList': string;
  'tagsListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
