// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailBlock': string;
  'detailComment': string;
  'detailField': string;
  'detailLabel': string;
  'detailLabelItalic': string;
  'formatsList': string;
  'releaseDetails': string;
  'tagsList': string;
  'tagsListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
