// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAnotherRow': string;
  'heading': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
