import { app, BrowserWindow, ipcMain } from "electron";
import electronSquirrelStartup from "electron-squirrel-startup";

import { fetchArtists } from "@/db/artists";
import type { FetchArtistsParams } from "@/types/artists";
import { createWindow } from "@/utils/appWindow";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const ARTISTS_WINDOW_WEBPACK_ENTRY: string;
declare const ARTISTS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (electronSquirrelStartup) {
  app.quit();
}

const createMainWindow = () =>
  createWindow({
    preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    html: MAIN_WINDOW_WEBPACK_ENTRY,
  });

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
await app.whenReady().then(async () => {
  ipcMain.on("open-new-artists-window", () => {
    ipcMain.handle("fetch-artists", (_, params: FetchArtistsParams) =>
      fetchArtists(params),
    );

    void createWindow({
      preload: ARTISTS_WINDOW_PRELOAD_WEBPACK_ENTRY,
      html: ARTISTS_WINDOW_WEBPACK_ENTRY,
    });
  });

  await createMainWindow();

  app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
      void createMainWindow();
    }
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
