// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAnotherRow': string;
  'controlWithRemove': string;
  'heading': string;
  'inputValueBlock': string;
  'labelVisuallyHidden': string;
  'removeCross': string;
  'removeCrossSlot': string;
  'section': string;
  'segment': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
