// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkboxLabel': string;
  'checkboxRow': string;
  'field': string;
  'heading': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
